### ISSUE TITLE
[Bug] When using container, WorldmapView is overlapping other Control widgets.

### ISSUE THREAD

**Issue by Abab-bk** [don-tnowe/godot-worldmap-builder#3]
In Editor:
![image](https://github.com/don-tnowe/godot-worldmap-builder/assets/55276676/4c07b7ff-88e6-432e-a550-cbca15e24fd6)
Runnig:
![image](https://github.com/don-tnowe/godot-worldmap-builder/assets/55276676/fd5eb24f-da19-4264-98d3-6487dd8dda04)
Furthermore, I have noticed that adding other nodes to WorldmapView results in an error :
![image](https://github.com/don-tnowe/godot-worldmap-builder/assets/55276676/c0bedcfb-1143-4e2f-b505-c16b726ac471)
![image](https://github.com/don-tnowe/godot-worldmap-builder/assets/55276676/e86bfa14-cd26-42e0-85d1-2e03db31ab95)

**Comment by don-tnowe** [comment]
Ah, it doesn't overlap - rather, it becomes super huge because of how minimum size is calculated. I'll allow to disable it and add a description note.

And yeah, non-`WMViewItem` nodes should be allowed, this allowed snapping graph points onto them but I forgot it while adding features :/.

Thank you!

**Comment by don-tnowe** [comment]
Should be up, but I'm also working on a fix for when node positions are negative, which will arrive later.
